In [50]:
import numpy as np

data = [[1, 2, 3], [5, 2, 0], [3, 2, 6], [5, 2, 4]]
print data
# avg = [float(sum(col))/len(col) for col in zip(*data)]
# print avg
D = np.array(data)
prd_M = np.dot(D, D.T)  # inner product for vector pairs
len_v = np.sqrt(np.sum(np.square(D), axis=1))  # for each row
len_M = np.dot(np.array([len_v]).T, np.array([len_v]))
inprd_M = np.divide(prd_M, len_M)
print inprd_M
print inprd_M.diagonal(3)
inprd_list = []
for i in range (1, inprd_M.shape[0]):
    inprd_list.extend(inprd_M.diagonal(i))
print inprd_list

[[1, 2, 3], [5, 2, 0], [3, 2, 6], [5, 2, 4]]
[[ 1.          0.4466625   0.95450444  0.83666003]
 [ 0.4466625   1.          0.5040302   0.80277297]
 [ 0.95450444  0.5040302   1.          0.91572308]
 [ 0.83666003  0.80277297  0.91572308  1.        ]]
[ 0.83666003]
[0.44666250028691867, 0.50403020362342643, 0.91572307649991391, 0.95450443540151564, 0.80277297191948638, 0.83666002653407545]


In [38]:
import math
9 / (math.sqrt(14) * math.sqrt(29))

0.4466625002869187

In [55]:
l = np.array([1, 2, 1])
print np.max(l)

2
